#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 15 10:08:41 2021

@author: AnnaNardelli
"""
import requests
  
url = "https://raw.githubusercontent.com/annanardelli/SRP2021/main/CS104ABETSyllabus.txt"
page = requests.get(url)
print(page.text)
